'use strict';

const _          = require('lodash');
const co         = require('co');
const AWS        = require('aws-sdk');
const apigateway = new AWS.APIGateway();
const cloudwatch = new AWS.CloudWatch();

const alarmActions = (process.env.alarm_actions || '').split(',');
const okAction     = (process.env.ok_actions || '').split(',');

let enableDetailedMetrics = co.wrap(function* (restApiId, stageName) {
  let getResp = yield apigateway.getStage({ restApiId, stageName }).promise();
  console.log('get stage settings' + '-----' + getResp.methodSettings);

  let isDetailedMetricsEnabled = _.get(getResp, 'methodSettings.*/*.metricsEnabled', false);
  if (isDetailedMetricsEnabled) {
    console.log('detailed metrics already enabled' + '-----' + { restApiId, stageName });
  } else {
    let updateReq = {
      restApiId,
      stageName,
      patchOperations: [
        {
          path: "/*/*/metrics/enabled",
          value: "true",
          op: "replace"
        }
      ]
    };
    yield apigateway.updateStage(updateReq).promise();
    console.log('enabled detailed metrics' + '-----' + { restApiId, stageName });
  }
});

let getRestEndpoints = co.wrap(function* (restApiId) {
  let resp = yield apigateway.getResources({ restApiId }).promise();
  console.log('got REST resources' + '-----' + { restApiId });

  let resourceMethods = resp.items.map(x => {
    let methods = _.keys(x.resourceMethods);
    return methods.map(method => ({ resource: x.path, method }));
  });

  return _.flattenDeep(resourceMethods);
});

let getRestApiName = co.wrap(function* (restApiId) {
  let resp = yield apigateway.getRestApi({ restApiId }).promise();
  console.log('got REST api' + '-----' + { restApiId });

  return resp.name;
});

let createAlarmsForEndpoints = co.wrap(function* (restApiId, stageName) {
  let apiName = yield getRestApiName(restApiId);
  console.log('`API name is ${apiName}`' + '-----' + { restApiId, stageName });

  let restEndpoints = yield getRestEndpoints(restApiId);
  console.log('got REST endpoints' + '-----' + { restApiId, stageName, restEndpoints });

  for (let endpoint of restEndpoints) {
    // let putReq = {
    //   AlarmName: `API [${apiName}] stage [${stageName}] ${endpoint.method} ${endpoint.resource} : p99 > 1s`,
    //   MetricName: 'Latency',
    //   Dimensions: [
    //     { Name: 'ApiName',  Value: apiName },
    //     { Name: 'Resource', Value: endpoint.resource },
    //     { Name: 'Method',   Value: endpoint.method },
    //     { Name: 'Stage',    Value: stageName }
    //   ],
    //   Namespace: 'AWS/ApiGateway',
    //   Threshold: 1000,      // 1s
    //   ComparisonOperator: 'GreaterThanThreshold',      
    //   Period: 60,           // per min
    //   EvaluationPeriods: 5, 
    //   DatapointsToAlarm: 5, // 5 consecutive mins to trigger alarm
    //   ExtendedStatistic: 'p99',
    //   ActionsEnabled: true,
    //   AlarmActions: alarmActions,
    //   AlarmDescription: `auto-generated by Lambda [${process.env.AWS_LAMBDA_FUNCTION_NAME}]`,
    //   OKActions: okAction,
    //   Unit: 'Milliseconds'
    // };
    let putReq = {
      AlarmName: `API [${apiName}] stage [${stageName}] ${endpoint.method} ${endpoint.resource} : Errors >= 1s`,
      MetricName: 'Errors',
      Dimensions: [
        { Name: 'ApiName',  Value: apiName },
        { Name: 'Resource', Value: endpoint.resource },
        { Name: 'Method',   Value: endpoint.method },
        { Name: 'Stage',    Value: stageName }
      ],
      Namespace: 'AWS/Lambda',
      Threshold: 1,      // 1s
      ComparisonOperator: 'GreaterThanOrEqualToThreshold',      
      Period: 60,           // per min
      EvaluationPeriods: 5, 
      DatapointsToAlarm: 5, // 5 consecutive mins to trigger alarm
      Statistic: 'Sum',
      ActionsEnabled: true,
      AlarmActions: alarmActions,
      AlarmDescription: `auto-generated by Lambda [${process.env.AWS_LAMBDA_FUNCTION_NAME}]`,
      OKActions: okAction,
      Unit: 'Count'
    };
    yield cloudwatch.putMetricAlarm(putReq).promise();
  }

  console.log('auto-created latency ALARMS for REST endpoints' + '-----' + { restApiId, stageName, restEndpoints });
});

module.exports.handler = co.wrap(function* (event, context, cb) {
  let restApiId = event.detail.requestParameters.restApiId;
  let stageName = event.detail.requestParameters.createDeploymentInput.stageName;

  //yield enableDetailedMetrics(restApiId, stageName);

  yield createAlarmsForEndpoints(restApiId, stageName);

  cb(null, 'ok');
});