service: cloudwatch-autogenerate-alarms

plugins:
  - serverless-pseudo-parameters
  - serverless-iam-roles-per-function

provider:
  name: aws
  runtime: nodejs8.10
  stage: ${opt:stage, 'dev'}

functions:
  autogenerate-api-alarms:
    handler: autogenerate-alarm.handler
    events:
      - cloudwatchEvent:
          event:
            source:
              - aws.lambda
            detail-type:
              - AWS API Call via CloudTrail
            detail:
              eventSource:
                - lambda.amazonaws.com
              eventName:
                - CreateFunction20150331
    environment:
      alarm_actions: arn:aws:sns:#{AWS::Region}:#{AWS::AccountId}:cloudwatch-alarm-notification
      ok_actions: arn:aws:sns:#{AWS::Region}:#{AWS::AccountId}:cloudwatch-alarm-notification
    iamRoleStatementsName: cloudwatch-auto-alarm-role
    iamRoleStatements:
      - Effect: Allow
        Action: cloudwatch:PutMetricAlarm
        Resource: "*"

resources:
  Resources:
    cloudwatchAlarmNotification:
      Type: AWS::SNS::Topic
      Properties:
        DisplayName: cloudwatch-alarm-notification
        TopicName: cloudwatch-alarm-notification

